### ISSUE TITLE
Fail to run "pip install -r requirements.txt"

### ISSUE THREAD

**Issue by VivianH61** [prosysscience/JSS#16]
I'm using mac and what I run this command, there is an ERROR "Could not install packages due to an OSError: [Errno 2] No such file or directory: '/System/Volumes/Data/home/conda/feedstock_root/build_artifacts/adal_1591523462562/work'". I wonder how to solve this problem.... Thanks in advance :)

**Comment by ingambe** [comment]
It seems that pip failed to install **adal** dependency.

However, this dependency is not actually used on this project.
The requirements file was a bit messy because it comes from a [docker container](gcr.io/deeplearning-platform-release/tf2-gpu.2-2).

I've updated the requirements file to contains only useful dependencies and tried a clean install on our server successfully.
Tell me if you still face any issue :)

**Comment by VivianH61** [comment]
Thanks for updating the requirement.txt!!! It does work.😁
